### ISSUE TITLE
Keep all the rows open

### ISSUE THREAD

**Issue by djaygit** [KiranJasvanee/KJExpandableTableTree#2]
How do i keep the parent. childs, sub childs initially open?

**Comment by bluelabeldeveloper1** [comment]
Library updated to support it. 
set `isInitiallyExpanded` to `true` after initialised library with your data.
`kjtreeInstance.isInitiallyExpanded = true`

**Comment by KiranJasvanee** [comment]
Library updated to support it. 
set `isInitiallyExpanded` to `true` after initialised library with your data.
`kjtreeInstance.isInitiallyExpanded = true`

**Comment by djaygit** [comment]
great thanks, i will a solution myself, but will update it.
